apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-cluster-user-auth
  namespace: flux-system
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: DOPPLER_TOKEN
            name: doppler-token-weave-gitops-secret
      nameTransformer: camel
---
apiVersion: v1
data:
  DataCamel: |
    {{- range $key, $value := . }}
    {{- if not (eq $key "dopplerConfig" "dopplerEnvironment" "dopplerProject") }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
kind: ConfigMap
metadata:
  name: doppler-filter-tpl
  namespace: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  dataFrom:
    - find:
        name:
          regexp: ".*"
  secretStoreRef:
    kind: SecretStore
    name: doppler-cluster-user-auth
  target:
    deletionPolicy: Delete
    name: cluster-user-auth
    template:
      templateFrom:
        - configMap:
            items:
              - key: DataCamel
                templateAs: KeysAndValues
            name: doppler-filter-tpl
          target: Data
