apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: rkt@bikeshed.dev
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: CLOUDFLARE_API_TOKEN
              name: cloudflare-credential
        selector:
          dnsNames:
            - harbor.bikeshed.dev
