apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../catalog/capacitor.yaml
  - ../../../catalog/kata-deploy/k3s
  - ../../../catalog/node-exporter.yaml
  - ../../../catalog/node-problem-detector.yaml
  - ../../../catalog/prometheus-community.yaml
