apiVersion: v1
data:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:Ok18zyamZJnKJD0d9JSrer/sWpZNKdHBhOggYYqU+Fx3W/De4LiEIye9rM2l5JFmNVhXNL35HqNPopyM32niYUxoXrWAm8e1ExLj/izAxgosi70kgoVGkEaNPI/pXdxe,iv:SnPgAYC6fiRKQ9Bbo+Wb/mD846w7+FtenLSpXJShdaA=,tag:UhUq03gUxogvx01+tKZGSg==,type:str]
kind: Secret
metadata:
    name: doppler-token-harbor-secret
    namespace: harbor
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cn360ndmrrgv0tvpu2gnl3p8lhg69k8t9vhnzwhg35cwmzqhg6smygcrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIODRUYUhiY3NmWnY2bk5U
            bGlCWTkvakh1d2ZXTEUwUVFVTWNHdHNkSERZCm92eXQ3Q3Fnd29iTGtqMVRwZGU4
            NW56OEk4c3JzaG1IYWVnWnlkN1dZUDgKLS0tIG5wU3RIb09aL0J2d1Q3QWN5UXhU
            R3FqdUJoK0NOYk94MnFIbUg3UDJMQWMKOjF2WIm1hE/2QldyuwBOG6/LEp+9QYoF
            hSMlqjDZhqgfGod0ghBm/eCNbYgF7MANi8SfRESO+dCizAhW27/w3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T13:30:49Z"
    mac: ENC[AES256_GCM,data:WqJJbIdU7rpEz6tGErgf23Sl+ElBe/A+WtxNMaIS/GXT6nm/ztbSb9/sMhS6rtRckKcl6acDB/HZZURHIKFNWH/6f8KvrY/2rclZL5pH9Eiv/AQNB3D4vCyfUcr3fVCdXwE2DVaJzV7bnJQ/ZPdfsMUTbjeD+RDoOdiQtfAjPL0=,iv:XvVX6YccyFtkUHkqY89+A2NDrqtIz918uEDMbLD6uUc=,tag:mU+rWvkgKOxNcwoYeuiGjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:rzWc9PKI9TOHdNZnqk68p2c92o6i7F59jIw8vKQO0PnKzPhbSjLDSk/AgoWP5X2gW0CijxIKq5cehp6eYNF/LbYGgf1p7lutpfSzum3FVxMAKSC4fO70+9PXD2Y=,iv:WSuog0YJu1ZkIJ7gscLMkYwnzMWCFyQr9eHyhvUsbH8=,tag:yusSLIs36ZYWaLYztgBuXg==,type:str]
kind: Secret
metadata:
    name: doppler-token-minio-secret
    namespace: harbor
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cn360ndmrrgv0tvpu2gnl3p8lhg69k8t9vhnzwhg35cwmzqhg6smygcrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIODRUYUhiY3NmWnY2bk5U
            bGlCWTkvakh1d2ZXTEUwUVFVTWNHdHNkSERZCm92eXQ3Q3Fnd29iTGtqMVRwZGU4
            NW56OEk4c3JzaG1IYWVnWnlkN1dZUDgKLS0tIG5wU3RIb09aL0J2d1Q3QWN5UXhU
            R3FqdUJoK0NOYk94MnFIbUg3UDJMQWMKOjF2WIm1hE/2QldyuwBOG6/LEp+9QYoF
            hSMlqjDZhqgfGod0ghBm/eCNbYgF7MANi8SfRESO+dCizAhW27/w3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T13:30:49Z"
    mac: ENC[AES256_GCM,data:WqJJbIdU7rpEz6tGErgf23Sl+ElBe/A+WtxNMaIS/GXT6nm/ztbSb9/sMhS6rtRckKcl6acDB/HZZURHIKFNWH/6f8KvrY/2rclZL5pH9Eiv/AQNB3D4vCyfUcr3fVCdXwE2DVaJzV7bnJQ/ZPdfsMUTbjeD+RDoOdiQtfAjPL0=,iv:XvVX6YccyFtkUHkqY89+A2NDrqtIz918uEDMbLD6uUc=,tag:mU+rWvkgKOxNcwoYeuiGjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
