apiVersion: v1
data:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:NpBPr6x5Yeie9I4WLHKLH7/fw5JZbukWweFcF7bGiXKx800mc1N/WyeBRPWspjnvYavlW6MW5p2f6mJbZAnWTVJYw0W511Lrf5gTnEYxd9lBddXRRSdiTAKYmvA=,iv:dkdh8iOj4skxCpUmlKcW38fxXfTgyF3w1rPlOpv1Z8k=,tag:ixpiVi6sWvgdR6YvejWyvA==,type:str]
kind: Secret
metadata:
    name: doppler-token-dex-credential
    namespace: dex
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cn360ndmrrgv0tvpu2gnl3p8lhg69k8t9vhnzwhg35cwmzqhg6smygcrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQREQ1d1FkZnZ2UTJ3aWE2
            dVROT2xEc2RlRWZ4NFpNU3FXcFY1Sk9ZM2tjCjJ1alpBQjFOT2JyUlJuUk9yV2Ey
            M3R0T3MyMWRGZzVHc3FyK0RqdnNEZFUKLS0tIHhmN1pucWJkT0FQRENkbmc2bFZy
            VkJPK2tKUGZkMGFTZGVmR2ZCbThSL0EKA6TdiGUTVdiKU+a3phLSKC/+Id9DhKhw
            Fs3goowYm7p7e5ri+Mj9AdPZNessyh9W04hKsireWmJnvVJIicDzOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T06:53:55Z"
    mac: ENC[AES256_GCM,data:ORKpYbbayTiO1QepfXSKpG6glE2ypeGEr+8C8xLGrez6JOxDcuK2ZAgf4HHf1aY36vCtzQHrOFlSedWtoY9n+taI+8QeykRA+tJH3m+vyKHU3c0JNJBWZU6chPQMmt+RZoP/PKKaIKx+USaUeEcOL2/5xu9Szz+eW4JTucRSxiE=,iv:b2GLzs2OX4LUT6ImBuLPOAYY9DrCHcRfFcI7x37BAOc=,tag:nRKSi3Wi7WeYjJjmnZFx7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
