apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../catalog/cert-manager.yaml
  - ../catalog/ingress-nginx.yaml
  - ../catalog/istio.yaml
  - ../catalog/kube-state-metrics.yaml
  - ../catalog/kubernetes-dashboard.yaml
  - ../catalog/metrics-server.yaml
  - ../catalog/node-exporter.yaml
  - ../catalog/weave-gitops.yaml
