apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /var/lib/rancher/k3s/agent/etc/containerd/
    target:
      group: apps
      kind: DaemonSet
      name: kata-deploy
      namespace: kube-system
      version: v1
resources:
  - ../base
