apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../external-secrets.yaml
  - ../../prometheus-operator-crds.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/dependsOn
        value:
          - name: prometheus-operator-crds
            namespace: kube-system
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      labelSelector: "type!=crd"
      version: v2beta1
