apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.4.0
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: OCIRepository
    name: capacitor
  targetNamespace: flux-system
  timeout: 5m
  wait: true
