apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
      version: 0.19.1
  interval: 1h
  values:
    serviceMonitor:
      enabled: ${ENABLE_SERVICE_MONITOR:=true}
