apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    digest: sha256:3a3db53303364f9be7846ab22578a44a1439a0839ee4166808affe22ad0d2e18
    #tag: 0.10.0
  url: oci://ghcr.io/external-secrets/charts/external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: external-secrets
  interval: 1h
  values:
    serviceMonitor:
      enabled: ${ENABLE_SERVICE_MONITOR:=true}
