apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.13.1
  interval: 1h
  values:
    interval: 10m
    policy: sync
    serviceMonitor:
      enabled: ${ENABLE_SERVICE_MONITOR:=true}
    sources:
      - ingress
    triggerLoopOnEvent: true
    txtOwnerId: external-dns
    txtPrefix: external-dns-
