apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    digest: sha256:b1a9d076d0433aef1f26f9fa298be052b3e286cee99265c0fd08d13aa942df42
    #tag: 0.10.5
  url: oci://ghcr.io/external-secrets/charts/external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: external-secrets
  interval: 1h
  values:
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
    image:
      repository: ghcr.io/external-secrets/external-secrets
    serviceMonitor:
      enabled: ${ENABLE_SERVICE_MONITOR:=true}
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
