apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    digest: sha256:a3b9a5e3a847a4be4212ef01ee2a0b85e408632972ecc1d7ead3a3b839972183
    #tag: 0.10.7
  url: oci://ghcr.io/external-secrets/charts/external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: external-secrets
  interval: 1h
  values:
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
    image:
      repository: ghcr.io/external-secrets/external-secrets
    serviceMonitor:
      enabled: ${ENABLE_SERVICE_MONITOR:=true}
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
