apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.0
  interval: 1h
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: ${ENABLE_SERVICE_MONITOR:=true}
      service:
        ipFamilies:
          - IPv4
          - IPv6
        ipFamilyPolicy: PreferDualStack
        nodePorts:
          http: 32080
          https: 32443
        type: ${GATEWAY_SERVICE_TYPE:=NodePort}
