apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 24h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.24.1
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.24.1
  dependsOn:
    - name: istio-base
  interval: 1h
  values:
    global:
      proxy:
        clusterDomain: ${CLUSTER_DOMAIN:=cluster.local}
    meshConfig:
      defaultConfig:
        proxyMetadata:
          ISTIO_DUAL_STACK: "true"
      trustDomain: ${CLUSTER_DOMAIN:=cluster.local}
    pilot:
      autoscaleEnabled: false
      env:
        ISTIO_DUAL_STACK: "true"
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.24.1
  dependsOn:
    - name: istiod
  interval: 1h
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.24.1
  dependsOn:
    - name: istiod
  interval: 1h
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: 1.24.1
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 1h
  values:
    autoscaling:
      enabled: false
    imagePullPolicy: IfNotPresent
    service:
      ipFamilyPolicy: PreferDualStack
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          nodePort: 31080
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          nodePort: 31443
          port: 443
          protocol: TCP
          targetPort: 443
      type: ${GATEWAY_SERVICE_TYPE:=NodePort}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
