apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 24h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.18.0
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.18.0
  dependsOn:
    - name: istio-base
  interval: 1h
  values:
    global:
      proxy:
        clusterDomain: ${CLUSTER_DOMAIN:=cluster.local}
    meshConfig:
      trustDomain: ${CLUSTER_DOMAIN:=cluster.local}
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: 1.18.0
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: add
                path: /spec/ipFamilyPolicy
                value: PreferDualStack
            target:
              kind: Service
              name: istio-ingressgateway
              namespace: istio-ingress
              version: v1
  values:
    service:
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          nodePort: 31080
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          nodePort: 31443
          port: 443
          protocol: TCP
          targetPort: 443
      type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
