apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 5.27.0
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
    namespace: kube-system
  interval: 1h
  values:
    prometheus:
      monitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
