apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 61.1.1
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
  interval: 1h
  values:
    crds:
      enabled: false
    grafana:
      enabled: true
      env:
        GF_USERS_DEFAULT_THEME: light
      persistence:
        enabled: enable
        size: 10Gi
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
