apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 5.16.1
  interval: 1h
  values:
    prometheus:
      monitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
