apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-system
      version: 58.2.2
  interval: 1h
  values:
    crds:
      enabled: false
    grafana:
      enabled: true
      env:
        GF_USERS_DEFAULT_THEME: light
      persistence:
        enabled: enable
        size: 10Gi
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
