apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 24h
  url: https://charts.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 5.3.0
  interval: 1h
  values:
    buckets:
      - name: minio
    existingSecret: minio-secret
    metrics:
      serviceMonitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
        includeNode: true
    mode: standalone
    persistence:
      size: 50Gi
    replicas: 1
    resources:
      requests:
        memory: 1Gi
