apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 2.3.16
  url: oci://ghcr.io/deliveryhero/helm-charts/node-problem-detector
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: node-problem-detector
    namespace: kube-system
  interval: 1h
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
