apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 4.23.2
  interval: 1h
  values:
    prometheus:
      monitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
