apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.deliveryhero.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: node-problem-detector
      version: 2.3.11
  interval: 1h
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: ${ENABLE_SERVICE_MONITOR:=true}
