apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 16.0.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    type: crd
  name: prometheus-operator-crds
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
    namespace: kube-system
  interval: 1h
