apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 24h
  url: https://seaweedfs.github.io/seaweedfs/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  chart:
    spec:
      chart: seaweedfs
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
      version: 3.80
  interval: 1h
  values:
    filer:
      data:
        size: 10Gi
        type: persistentVolumeClaim
      logs:
        size: 10Gi
        type: persistentVolumeClaim
      s3:
        enableAuth: true
        enabled: true
    global:
      monitoring:
        enabled: true
    master:
      data:
        size: 10Gi
        type: persistentVolumeClaim
      logs:
        size: 10Gi
        type: persistentVolumeClaim
    volume:
      dataDirs:
        - maxVolumes: 0
          name: data1
          size: 50Gi
          type: persistentVolumeClaim
