apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 1.76.1
  interval: 1h
  values:
    operatorConfig:
      extraEnv:
        - name: OPERATOR_DEFAULT_LOAD_BALANCER
          value: "true"
      hostname: ${CLUSTER_NAME:=tailscale-operator}
      image:
        pullPolicy: IfNotPresent
    proxyConfig:
      defaultProxyClass: default
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        imagePullPolicy: IfNotPresent
