apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      group: apps
      kind: Deployment
      name: gateway-api-admission-server
      version: v1
resources:
  - ../../cert-manager.yaml
  - ../../external-secrets.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/standard-install.yaml
