apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stack
  namespace: flux-system
spec:
  dependsOn:
    - name: prelude
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/values/externalURL
          value: http://172.20.24.10:30002
        - op: add
          path: /spec/values/proxy
          value:
            httpsProxy: http://172.24.0.1:6666
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: harbor
        namespace: harbor
        version: v2beta1
  path: ./clusters/default-overlay/stack
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
