apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stack
  namespace: flux-system
spec:
  dependsOn:
    - name: prelude
  interval: 1h
  path: ./clusters/default-overlay/stack
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
