apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stack
  namespace: flux-system
spec:
  dependsOn:
    - name: prelude
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/values/expose
          value:
            ingress:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                cert-manager.io/private-key-algorithm: ECDSA
                cert-manager.io/private-key-rotation-policy: Always
              className: istio
              hosts:
                core: harbor.bikeshed.dev
            tls:
              enabled: true
            type: ingress
        - op: replace
          path: /spec/values/externalURL
          value: https://harbor.bikeshed.dev:31443
        - op: add
          path: /spec/values/proxy
          value:
            httpsProxy: http://172.24.0.1:6666
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: harbor
        namespace: harbor
        version: v2beta1
  path: ./clusters/default-overlay/stack
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
