apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stack
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: prelude
  interval: 1h
  patches:
    - patch: |
        - op: add
          path: /spec/values/domainFilters
          value:
            - bikeshed.dev
        - op: add
          path: /spec/values/env
          value:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CF_API_TOKEN
                  name: cloudflare-credential
        - op: add
          path: /spec/values/provider
          value: cloudflare
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: external-dns
        namespace: external-dns
        version: v2
    - patch: |
        - op: replace
          path: /spec/values/prometheus/prometheusSpec/scrapeClasses
          value:
            - default: true
              name: default
              relabelings:
                - replacement: ${CLUSTER_NAME}
                  targetLabel: cluster
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: kube-prometheus-stack
        version: v2
  path: ./clusters/overlay/default/stack
  postBuild:
    substitute:
      CLUSTER_NAME: local-k3s
      GATEWAY_SERVICE_TYPE: LoadBalancer
      var_substitution_enabled: "true"
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
