apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stack
  namespace: flux-system
spec:
  dependsOn:
    - name: prelude
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/values/global/proxy/clusterDomain
          value: fleet.local
        - op: replace
          path: /spec/values/meshConfig/trustDomain
          value: fleet.local
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: istiod
        namespace: istio-system
        version: v2beta1
  path: ./clusters/fleet-overlay/stack
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
