apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-oci-credential
  namespace: envoy-gateway-system
spec:
  provider:
    pulumi:
      accessToken:
        secretRef:
          key: PULUMI_ACCESS_TOKEN
          name: pulumi-credential
      environment: harbor
      organization: vac
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-credential
  namespace: envoy-gateway-system
spec:
  dataFrom:
    - extract:
        key: oci-credential
  secretStoreRef:
    kind: SecretStore
    name: pulumi-oci-credential
  target:
    deletionPolicy: Delete
    name: oci-credential
