apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: pulumi-oci-credential
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - namespaceSelector:
        matchLabels:
          manage-oci-credential: enabled
  provider:
    pulumi:
      accessToken:
        secretRef:
          key: PULUMI_ACCESS_TOKEN
          name: pulumi-credential
          namespace: external-secrets
      environment: local-k3s
      organization: vac
      project: infra
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: oci-credential
spec:
  externalSecretSpec:
    dataFrom:
      - extract:
          key: oci-credential
    secretStoreRef:
      kind: ClusterSecretStore
      name: pulumi-oci-credential
    target:
      deletionPolicy: Delete
      name: oci-credential
      template:
        type: kubernetes.io/dockerconfigjson
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: kube-system
    - matchLabels:
        manage-oci-credential: enabled
