apiVersion: v1
data:
    PULUMI_ACCESS_TOKEN: ENC[AES256_GCM,data:MuSrlrR7hgC+idHVQbAI6K6ag2hhU+l9IokYXQbOSUKwbtwphdDZvUdfBLnY1v14ukJ3Ou2AEKD6Mq0I,iv:IbqkKokcXLkCaMIqvhzC9Z5mliHoFVN/IO4YBTbs0UY=,tag:EBJ0SG3DT2/tpuJBTPtX9Q==,type:str]
kind: Secret
metadata:
    name: pulumi-credential
    namespace: external-secrets
type: Opaque
sops:
    age:
        - recipient: age1dt6l96yjfvjfat8c4cs6hwz64hh8zzs2wpjw0u609srddxzppvgsd63jsd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpejJmUG5GV3lSWEV6UmFR
            TVh5U05WYnJ0STVvRXkydktlTmxlSWhlOUJFCi9Bb2N5cG03VU5BTXNWRWZwRXRa
            amZXMkJ6ekNtc0hkbzdtcktQZGR5cjgKLS0tIDlUWExaekxEMzhsd0dEbDRlaWo2
            a1VjTXp1ZTg2SWdnSUZtNk1YeG80Y2MKVzxtPm+HvFSbrBfNlswCwYvuVFNWeJzm
            9zneYmhyolcxvs1aZFx6/fAGv3fWE73ZsGgiTaX5vufeWeCiPaPKZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:31:16Z"
    mac: ENC[AES256_GCM,data:6v0ab/eyl4eyy6mfcgmS3ErDuayYvEWHYHVuVofmhimKJBiJGeb+Fa3+f2aYrFwiu1doJ0L68c5a5S68TKnkXzKQpF83gIVx/3a+4w3PCnJfBn9EGm0/bjf/+SaSTym40FQ6qhzogmY9cHYaMcjbe7G0Pp6zM6VgryaBkEYfA4c=,iv:3FmhbZx74Y+0zcz2WtxUnUcjGM/n6ZQuowz+UMHP/Cw=,tag:INTlf0ltRiIi8aKWmnR8aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
