apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-cluster-user-auth
  namespace: flux-system
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: DOPPLER_TOKEN
            name: doppler-token-weave-gitops-secret
      nameTransformer: camel
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  dataFrom:
    - find:
        name:
          regexp: ".*"
  secretStoreRef:
    kind: SecretStore
    name: doppler-cluster-user-auth
  target:
    name: cluster-user-auth
