apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgDA/DZZm3iQCVhfkyFioaOmCiuP9H+bUzUW7Nkx20z4Bs/37X2Udb7jabDW0N5nrNCrxhjDcsdQtmddysNCfAZ8c++EYvebO7ZZRHeXvre4qJGIYJotoOo1FA+rrqQP6FVeVtNYOEVzrZcv7B7xnheantjeUJVUcbIdITTM2ZJsLILu2a/rFV0ijn/UKnQZ7kX4nLOzO5KwTwMY2lsCtfainWDnoFjQybY3TEacFdKocy1rPzm6iOS8gAGq5rXLyVgjUpBFRa8mTjL+jaJ57I9sV5pPgaiP1gKCm2/FpfCa2gZOCWQUWy3tHux5/C4673Q3KCLe7NH2HaQjSlKfyLyqeszxBAO+YmpZx4T69hmtX8oCljBThwxDdznUggy0upbDdmPVIoHVL0JqPJABkKq7HcAQsQ0SJ8/vve140hir5XUu/PfLK1jlg08/IZjkWnixijYOTLDERW1F/yzWCWuMHYPYtVM20Yg6FbnjI2f7Po/vCLQJuABUyNluutek1CV5LeAtC782eECs4xavycHxYXoLSGO5rBRXRQt1D3lt9UETfQoMPaNYNxssS8dhkf2LNhGJKvQyvrlZTBGElheau2mweEzZxx3K/KzCmkdPnaVRaYqM2xMN5ASXw4OmnYZfWc8Bs+cwS1ecIGmkwUeJ1Adqol/UAkwi46MvyjhC8loxG2irIsaoLsveoMg6TijFAmAO93Cl4+QCDhL9Sdy7vbqxhZvA5unOyf6ZeHBDo3HdtDfkpdL0DeshIrolJTDjxmUlwHZNpXS8eYg=
    username: AgDJYNvQSgQQNkiR4PoNRE+D6sWj5jaPYzbFtKasjBgLFXqr2uOKc76H5H5Rs+FRPrsIGMZzPrxH96PkUq3x1FZnrB04hkxjk8/kom0XymElHjVkoeJrDVtIeR8gmZgmzkfa0qHWQS2nLrbVr16zh49+Cu72SIBxulEWiQz/S5VHCTHAZn5mTYk9Jbd0rXZLFEP2FlrOYoCI53ootMs/qaWfQLfverM50YTKm0VY5n0B/8EubBGerj3M6ycLF5dDrhZWrLgjUmjXZHm41s1ggSfIKcNqiGNU4PCR63C8TU7mPgjgfiDOmdAqe4M/horcyF4cPBHkuyfL2S5LOz/Ad/nWtmcwGIVBCbwiIXUfwuNzmlGF5UBZvjJfki0jVdBH/rI4rXZCmmjiLs2RkP7L9jqjW2jIKAbd2T5PQzcneHbbCDGTf3E+AJ0CDhDBJ+/XfLSvYEzPA2YbPONJvTTU+aUqFmPFoyygqgoq9VI0KvvuoWVsExE001YBCWf+P41GutAaFTSTCB/9V+YigILlL2pypOyT6B+NKejNyFhg9D5KSOUMQdwZZGkTmklFDROra32y+k5JyFhLaGnUzWa44HP/dR+Nm4gvr1EUuOgRGdVNUWC0b5zNWkKALi2nmHiJf5Ob09X+sGmCtOQNXtaYkOHDCCSVKRBnzZuCKspQatEfJ7l9zMD99PdK/VdsRhfmRkzAJA7UhQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
